name: build-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - name: Build Default mod
        working-directory: ./vortexopt
        run: ./gradlew --no-daemon clean build -x test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: default-jars
          path: |
            vortexopt/build/libs/*.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            vortexopt/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

